
  CREATE TABLE "INZI"."TB_BATCH_CONVERT_STATUS" 
   (	"JOB_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"STATUS" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"FILE_PATH" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"START_TIME" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "INZI"."TB_BATCH_CONVERT_STATUS"."JOB_ID" IS '변환 요청 JOB ID';
   COMMENT ON COLUMN "INZI"."TB_BATCH_CONVERT_STATUS"."STATUS" IS '변환 상태(0:변환중, 1:변환성공)';
   COMMENT ON COLUMN "INZI"."TB_BATCH_CONVERT_STATUS"."FILE_PATH" IS '변환 대상 파일 경로';

